In [1]:
import numpy as np

import sys
sys.path.append("..")
import solax as sx

## 1. Basis

In [2]:
basis = sx.Basis(["1100", "1010", "1001", "0110", "0101", "0011"])

In [3]:
print(basis)

1100
1010
1001
0110
0101
...


In [4]:
with sx.dets_printing_limit(10):
    print(basis)

1100
1010
1001
0110
0101
0011


In [5]:
print(basis.bitlen)

4


In [6]:
print(len(basis))

6


In [7]:
print(basis[0])

1100


In [8]:
print(basis[0:3])

1100
1010
1001


In [9]:
print(basis[0, 1, 4])

1100
1010
0101


In [10]:
print(basis[True, True, False, False, True, False])

1100
1010
0101


In [11]:
print(basis == reversed(basis))

True


In [12]:
basis_even = basis[::2]
basis_odd = basis[1::2]

In [13]:
print(basis_even + basis_odd == basis)

True


In [14]:
print(basis + basis == basis)

True


In [15]:
print(basis % basis_even == basis_odd)

True


## 2. State

In [16]:
state = sx.State(basis, np.ones(6))

In [17]:
print(state)

|1100>  *  1.0
|1010>  *  1.0
|1001>  *  1.0
|0110>  *  1.0
|0101>  *  1.0
...


In [18]:
print(state.basis)

1100
1010
1001
0110
0101
...


In [19]:
print(state.coeffs)

[1. 1. 1. 1. 1. 1.]


In [20]:
state_odd = state % basis_even
print(state_odd)

|1010>  *  1.0
|0110>  *  1.0
|0011>  *  1.0


In [21]:
print(state_odd.basis == basis_odd)

True


In [22]:
print(2 * state)

|1100>  *  2.0
|1010>  *  2.0
|1001>  *  2.0
|0110>  *  2.0
|0101>  *  2.0
...


In [23]:
print(state * 1j)

|1100>  *  1j
|1010>  *  1j
|1001>  *  1j
|0110>  *  1j
|0101>  *  1j
...


In [24]:
print(state / 2)

|1100>  *  0.5
|1010>  *  0.5
|1001>  *  0.5
|0110>  *  0.5
|0101>  *  0.5
...


In [25]:
print(-state)

|1100>  *  -1.0
|1010>  *  -1.0
|1001>  *  -1.0
|0110>  *  -1.0
|0101>  *  -1.0
...


In [26]:
state1 = state[0, 1, 4]
print(state1)

|1100>  *  1.0
|1010>  *  1.0
|0101>  *  1.0


In [27]:
state2 = state[0, 3]
print(state2)

|1100>  *  1.0
|0110>  *  1.0


In [28]:
print(state1 + state2)

|1100>  *  2.0
|1010>  *  1.0
|0101>  *  1.0
|0110>  *  1.0


In [29]:
print(state1 - state2)

|1100>  *  0.0
|1010>  *  1.0
|0101>  *  1.0
|0110>  *  -1.0


In [30]:
print(0.1 + 0.1 - 0.2)
print(0.1 + 0.2 - 0.3)

0.0
5.551115123125783e-17


In [31]:
print(state1 * state2)

1.0


In [32]:
print(state * state)

6.0


In [33]:
state_normalized = state.normalize()
print(state_normalized * state_normalized)

1.0000000000000002


In [34]:
state3 = state2[-1]
state123 = state1 - state2 - state3
print(state123)

|1100>  *  0.0
|1010>  *  1.0
|0101>  *  1.0
|0110>  *  -2.0


In [35]:
state_chopped1 = state123.chop(1e-14)
print(state_chopped1)

|1010>  *  1.0
|0101>  *  1.0
|0110>  *  -2.0


In [36]:
state_chopped2 = state123.chop(1.5)
print(state_chopped2)

|0110>  *  -2.0


In [37]:
state_chopped3 = state123.chop(2.5)
print(state_chopped3)
print(len(state_chopped3))


0


In [38]:
state_mini = state[:2]
state_a = 0.1 * state_mini + 0.2 * state_mini
print(state_a)

|1100>  *  0.30000000000000004
|1010>  *  0.30000000000000004


In [39]:
state_b = 0.3 * state_mini
print(state_b)

|1100>  *  0.3
|1010>  *  0.3


In [40]:
state_diff = state_a - state_b
print(state_diff)

|1100>  *  5.551115123125783e-17
|1010>  *  5.551115123125783e-17


In [41]:
state_zero = state_diff.chop(1e-14)
print(len(state_zero))

0


## 3. OperatorTerm

In [42]:
daggers = (1, 0)

posits = np.array([
    [1, 3],
    [2, 4]
]) - 1

coeffs = np.array([
    1.0,
    1.0
])

In [43]:
V0 = sx.OperatorTerm(daggers, posits, coeffs)
print(V0)

OperatorTerm(
	daggers=(1, 0),
	posits=array([[0, 2],
	       [1, 3]]),
	coeffs=array([1., 1.])
)


In [44]:
print(V0.hconj)

OperatorTerm(
	daggers=(1, 0),
	posits=array([[2, 0],
	       [3, 1]]),
	coeffs=array([1., 1.])
)


In [45]:
V = V0 + V0.hconj
print(V)

OperatorTerm(
	daggers=(1, 0),
	posits=array([[0, 2],
	       [1, 3],
	       [2, 0],
	       [3, 1]]),
	coeffs=array([1., 1., 1., 1.])
)


In [46]:
basis = sx.Basis(["1001", "0110"])
coeffs = np.array([1.0, -1.0])

psi = sx.State(basis, coeffs)
psi = psi.normalize()

print(psi)

|1001>  *  0.7071067811865475
|0110>  *  -0.7071067811865475


In [47]:
result_psi = V(psi)
print(result_psi)

2024-08-20 15:52:26.344950: W external/xla/xla/service/gpu/nvptx_compiler.cc:765] The NVIDIA driver's CUDA version is 12.2 which is older than the ptxas CUDA version (12.5.82). Because the driver is older than the ptxas version, XLA is disabling parallel compilation, which may slow down compilation. You should update your NVIDIA driver or use the NVIDIA-provided CUDA forward compatibility packages.


|1100>  *  1.414213562373095
|0011>  *  1.414213562373095


In [48]:
result_basis = V(psi.basis)
print(result_basis)

1100
0011


In [49]:
result_psi_batches = V(psi, det_batch_size=1, op_batch_size=2)

In [50]:
s = result_psi_batches - result_psi
s = s.chop(1e-14)
print(len(s))

0


## 4. Operator

In [51]:
op = sx.Operator(daggers, posits, coeffs)
print(op)

Operator({
	(1, 0): OperatorTerm(
		daggers=(1, 0),
		posits=array([[0, 2],
		       [1, 3]]),
		coeffs=array([ 1., -1.])
	)
})


In [52]:
print(sx.Operator(V0))

Operator({
	(1, 0): OperatorTerm(
		daggers=(1, 0),
		posits=array([[0, 2],
		       [1, 3]]),
		coeffs=array([1., 1.])
	)
})


In [53]:
daggers_u = (1, 0, 1, 0)
posits_u = np.array([
    [1, 1, 2, 2],
    [3, 3, 4, 4]
]) - 1
coeffs_u = np.array([0.25, 0.75])

U = sx.Operator(daggers_u, posits_u, coeffs_u)
print(U)

Operator({
	(1, 0, 1, 0): OperatorTerm(
		daggers=(1, 0, 1, 0),
		posits=array([[0, 0, 1, 1],
		       [2, 2, 3, 3]]),
		coeffs=array([0.25, 0.75])
	)
})


In [54]:
H = 1 + V0 + V0.hconj + U
print(H)

Operator({
	(1, 0): OperatorTerm(
		daggers=(1, 0),
		posits=array([[0, 2],
		       [1, 3],
		       [2, 0],
		       [3, 1]]),
		coeffs=array([1., 1., 1., 1.])
	),
	scalar: 1,
	(1, 0, 1, 0): OperatorTerm(
		daggers=(1, 0, 1, 0),
		posits=array([[0, 0, 1, 1],
		       [2, 2, 3, 3]]),
		coeffs=array([0.25, 0.75])
	)
})


In [55]:
print(H[1, 0, 1, 0])

OperatorTerm(
	daggers=(1, 0, 1, 0),
	posits=array([[0, 0, 1, 1],
	       [2, 2, 3, 3]]),
	coeffs=array([0.25, 0.75])
)


In [56]:
print(H["scalar"])

1


In [57]:
for key in H.keys():
    print(key)

(1, 0)
scalar
(1, 0, 1, 0)


In [58]:
print(len(H))

3


In [59]:
for key, term in H.items():
    if key != "scalar":
        print(f"Length of the OperatorTerm {key} is {len(term)}")

Length of the OperatorTerm (1, 0) is 4
Length of the OperatorTerm (1, 0, 1, 0) is 2


In [60]:
H_without_V = H.drop(1, 0)
print((1, 0) in H_without_V)

False


In [61]:
H_without_scalar = H.drop("scalar")
print("scalar" in H_without_scalar)

False


In [62]:
H_chopped1 = H.chop((1, 0, 1, 0), 0.5)
print(len(H_chopped1[1, 0, 1, 0]))

1


In [63]:
H_chopped2 = H.chop((1, 0, 1, 0), 1.0)
print((1, 0, 1, 0) in H_chopped2)

False


## 5. OperatorMatrix

In [64]:
basis = sx.Basis(["1001", "1100", "0110", "0011"])

In [65]:
matrix = H.build_matrix(basis)
print(matrix)

OperatorMatrix(coord=array([[1, 0],
       [3, 0],
       [2, 1],
       [0, 1],
       [1, 2],
       [3, 2],
       [0, 3],
       [2, 3],
       [0, 0],
       [1, 1],
       [2, 2],
       [3, 3]]), val=array([ 1.  ,  1.  , -1.  ,  1.  , -1.  , -1.  ,  1.  , -1.  ,  1.  ,
        1.25,  1.  ,  1.75]), size=array([4, 4]))


In [66]:
print(matrix.size)

(4, 4)


In [67]:
print(matrix.num_nonzero)

12


In [68]:
coo_matrix = matrix.to_scipy()

In [69]:
dense_matrix = coo_matrix.todense()
print(dense_matrix)

[[ 1.    1.    0.    1.  ]
 [ 1.    1.25 -1.    0.  ]
 [ 0.   -1.    1.   -1.  ]
 [ 1.    0.   -1.    1.75]]


In [70]:
def print_matrix(m):
    print(m.to_scipy().todense())

In [71]:
print_matrix(matrix)

[[ 1.    1.    0.    1.  ]
 [ 1.    1.25 -1.    0.  ]
 [ 0.   -1.    1.   -1.  ]
 [ 1.    0.   -1.    1.75]]


In [72]:
print_matrix(
    matrix.displace(2, 1)
)

[[ 0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.  ]
 [ 0.    1.    1.    0.    1.  ]
 [ 0.    1.    1.25 -1.    0.  ]
 [ 0.    0.   -1.    1.   -1.  ]
 [ 0.    1.    0.   -1.    1.75]]


In [73]:
print_matrix(
    matrix.displace(-1, -1)
)

[[ 1.25 -1.    0.  ]
 [-1.    1.   -1.  ]
 [ 0.   -1.    1.75]]


In [74]:
print_matrix(
    matrix.window((1, 1), (3, 4))
)

[[ 0.    0.    0.    0.  ]
 [ 0.    1.25 -1.    0.  ]
 [ 0.   -1.    1.   -1.  ]
 [ 0.    0.    0.    0.  ]]


In [75]:
sub_basis = basis[0, 2]
print(sub_basis)

1001
0110


In [76]:
print_matrix(
    matrix.shrink_basis(basis, sub_basis)
)

[[1. 0.]
 [0. 1.]]


In [77]:
print_matrix(
    matrix.chop(1.1)
)

[[0.   0.   0.   0.  ]
 [0.   1.25 0.   0.  ]
 [0.   0.   0.   0.  ]
 [0.   0.   0.   1.75]]


In [78]:
matrix3_3 = matrix.displace(-1, -1)
print_matrix(matrix3_3)

[[ 1.25 -1.    0.  ]
 [-1.    1.   -1.  ]
 [ 0.   -1.    1.75]]


In [79]:
matrix5_2 = matrix.displace(1, -2)
print_matrix(matrix5_2)

[[ 0.    0.  ]
 [ 0.    1.  ]
 [-1.    0.  ]
 [ 1.   -1.  ]
 [-1.    1.75]]


In [80]:
print_matrix(
    matrix3_3 + matrix5_2
)

[[ 1.25 -1.    0.  ]
 [-1.    2.   -1.  ]
 [-1.   -1.    1.75]
 [ 1.   -1.    0.  ]
 [-1.    1.75  0.  ]]


In [81]:
m1 = matrix.window((0, 0), (2, 2))
print_matrix(m1)

[[1.   1.   0.   0.  ]
 [1.   1.25 0.   0.  ]
 [0.   0.   0.   0.  ]
 [0.   0.   0.   0.  ]]


In [82]:
m2 = matrix.shrink_basis(basis, basis[:2])
print_matrix(m2)

[[1.   1.  ]
 [1.   1.25]]


In [83]:
print(
    (m1 - m2).chop(1e-14).num_nonzero == 0
)

True


In [84]:
print(m1.size == m2.size)

False
